"""Agregar columna imagen a ubicaciones

Revision ID: 12d861ffd6e1
Revises: 4ccb6ff6ec8e
Create Date: 2025-09-20 21:57:26.228955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d861ffd6e1'
down_revision = '4ccb6ff6ec8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
